pipeline {
    
    agent any
    
    stages {

       stage('Do the deployment') {
            
            steps {
                echo ">> Run deploy applications "
            }
        }
    }
}
